### ISSUE TITLE
review

### ISSUE THREAD

**Issue by ale-strada** [RamiroRiggeri/desafio-m6-apx#1]
hola @RamiroRiggeri Como va? Felicitaciones, el juego funciona muy bien!! solo estaria bueno corregir un par de cosas. Por un lado, cuando uno de los dos jugadores no elige una jugada, se elige sola en ves de devolver algun error o anular esa jugada. Y por otro, deberias ver la forma de que no pueda entrar un 3er jugador a la sala, ya que este pisa a alguno de los que estaban jugando. Saludos!!

**Comment by RamiroRiggeri** [comment]
Hola Ale! Si el tema de que se elija sola lo hice así a propósito, pero lo modifico. Y tomo lo del 3er jugador, gracias!
